/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensl_example;

import android.util.Log;

public class opensl_example {
  public static void start_process() {
    opensl_exampleJNI.start_process();
  }

  public static void stop_process() {
    opensl_exampleJNI.stop_process();
  }

  public static short[] getBuffer() {
    short[] cPtr = opensl_exampleJNI.getBuffer();
    return cPtr;
  }

  public static void setBuffer(short[] data) {
    opensl_exampleJNI.setBuffer(data);
  }

}
