/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package opensl_example;

public class opensl_example {
  public static void start_process() {
    opensl_exampleJNI.start_process();
  }

  public static void stop_process() {
    opensl_exampleJNI.stop_process();
  }

  public static SWIGTYPE_p_short getBuffer() {
    long cPtr = opensl_exampleJNI.getBuffer();
    return (cPtr == 0) ? null : new SWIGTYPE_p_short(cPtr, false);
  }

  public static void setBuffer(SWIGTYPE_p_short data) {
    opensl_exampleJNI.setBuffer(SWIGTYPE_p_short.getCPtr(data));
  }

}
